# Generated by Django 4.2.3 on 2023-07-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
